site_name: 'Yncrea - Virtualization Course'

# Repository
repo_name: Labs solutions
repo_url: https://github.com/omerlin/yncrea-virtualization-labs
edit_uri: ""
site_description: >-
  This training material is part of <b> Virtualization Course</b> for <b>YNCREA Toulon.</b>
  <br><br>
  <i>The course takes place over three days and intends to give students
  an understanding of virtualization technologies with a focus on containers (Docker) and orchestrators (Kubernetes).</i>

nav:
  - Home: index.md

  - Day#1:
    - Env - Prerequisites: day1/10_prerequisites.md
    - Env - Windows WSL2: day1/12_windows_prerequisites.md    
    - Virtualization - Story and Concepts: day1/15_story_of_virtualization.md
    - Virtualization - Virtual Box: day1/20_virtualBox.md
    - Virtualization - Labs: day1/22_virtualBoxLabs.md
    - Virtualization - Docker machine: day1/30_dockerMachine.md
    - Docker - Basics: day1/32_dockerBasics.md
    - Docker compose: day1/34_dockerCompose.md


  - Day#2:
    - Day1 - quick summary: day2/day1Summary.md
    - Cloud - Introduction to Cloud: day2/cloudIntroduction.md
    - Kubernetes - introduction: day2/kubernetesIntroduction.md
    - Kubernetes - installation: day2/kubernetesInstallation.md
    - Kubernetes - basics: day2/kubernetesBasics.md

  - Day#3:
    - Day2 - quick summary: day3/day2Summary.md
    - Kubernetes - Advanced: day3/kubernetesAdvanced.md
    - Cloud - Google Cloud Platform: day3/GoogleCloudPlatform.md
    - Evaluation - Quizz: day3/quizz.md

  - Cheatsheets:
    - chocolatey: cheatsheets/choco.md
    - virtualBoxManage: cheatsheets/vboxManage.md
    - vagrant: cheatsheets/vagrant.md
    - docker: cheatsheets/docker.md
    - kubernetes: cheatsheets/kubernetes.md
    - WSL2: cheatsheets/wsl2.md

theme:
  language: en
  name: 'material'
  logo: files/yncrea.png
  favicon: files/yncrea.png
  palette:
    primary: blue
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - tabs
    - instant
  custom_dir: material

markdown_extensions:
  - def_list
  - footnotes
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
copyright: '&copy; 2021 Olivier Merlin'

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/omerlin
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/repository/docker/omerlin/srvquizz
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/olivier-merlin-90258a6

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto